# Generated by Django 4.0.2 on 2025-04-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_ticket_unique_ticket_row_seat_movie_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_row_seat',
        ),
    ]
